"""
Full submission verification.

Checks:
  1. Project structure — every required file/directory exists
  2. Python imports — every module loads cleanly
  3. Class/function contracts — key symbols present
  4. Configuration — settings, YAML, .env loaded
  5. Artifacts — inferred-events.jsonl and evaluation_report.json
  6. Docs — README, research log, solution doc, evaluation report
  7. Tests — pytest suite passes (offline tests only)

Run:
    python -m scripts.verify_submission
"""
from __future__ import annotations

import importlib
import json
import subprocess
import sys
from pathlib import Path

# Anchor to project root regardless of CWD
_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))


# ---------- check helpers ---------------------------------------------------

class Report:
    def __init__(self):
        self.passed = 0
        self.failed = 0
        self.warnings = 0
        self.failures: list[str] = []
        self.warnings_list: list[str] = []

    def ok(self, label: str):
        self.passed += 1
        print(f"  PASS   {label}")

    def fail(self, label: str, detail: str = ""):
        self.failed += 1
        self.failures.append(f"{label} — {detail}" if detail else label)
        print(f"  FAIL   {label}" + (f"  ({detail})" if detail else ""))

    def warn(self, label: str, detail: str = ""):
        self.warnings += 1
        self.warnings_list.append(f"{label} — {detail}" if detail else label)
        print(f"  WARN   {label}" + (f"  ({detail})" if detail else ""))

    def section(self, name: str):
        print()
        print(f"── {name} " + "─" * (60 - len(name)))


# ---------- section 1: files exist -----------------------------------------

REQUIRED_FILES = [
    # Root
    "README.md",
    "requirements.txt",
    "pytest.ini",
    ".env.example",
    ".gitignore",
    # Config
    "config/settings.py",
    "config/guardrails.yaml",
    "config/agents.yaml",
    # Streaming
    "src/streaming/__init__.py",
    "src/streaming/event_generator.py",
    "src/streaming/cep_engine.py",
    "src/streaming/features.py",
    "src/streaming/windows.py",
    # Memory
    "src/memory/__init__.py",
    "src/memory/schemas.py",
    "src/memory/decay.py",
    "src/memory/working_memory.py",
    "src/memory/episodic_memory.py",
    "src/memory/semantic_memory.py",
    "src/memory/state_board.py",
    # Guardrails
    "src/guardrails/__init__.py",
    "src/guardrails/scanner.py",
    "src/guardrails/pii.py",
    "src/guardrails/rbac.py",
    # Agents
    "src/agents/__init__.py",
    "src/agents/base_agent.py",
    "src/agents/schemas.py",
    "src/agents/usage_agent.py",
    "src/agents/support_agent.py",
    "src/agents/transaction_agent.py",
    "src/agents/kyc_agent.py",
    "src/agents/life_event_agent.py",
    "src/agents/synthesis_agent.py",
    "src/agents/debate_agent.py",
    "src/agents/judge_agent.py",
    "src/agents/action_agent.py",
    "src/agents/critique_agent.py",
    # Orchestration
    "src/orchestration/__init__.py",
    "src/orchestration/no_action_gate.py",
    "src/orchestration/pipeline.py",
    # HITL
    "src/hitl/__init__.py",
    "src/hitl/approval_queue.py",
    # Output
    "src/output/__init__.py",
    "src/output/schema.py",
    "src/output/inferred_events_writer.py",
    # Evaluation
    "src/evaluation/__init__.py",
    "src/evaluation/metrics.py",
    "src/evaluation/scoring_harness.py",
    # Utils
    "src/utils/__init__.py",
    "src/utils/logger.py",
    "src/utils/tracing.py",
    "src/utils/llm_client.py",
    # Scripts
    "scripts/__init__.py",
    "scripts/run_full_pipeline.py",
    "scripts/run_evaluation.py",
    "scripts/smoke_stream.py",
    "scripts/smoke_memory.py",
    "scripts/smoke_swarm.py",
    "scripts/verify_phase2.py",
    # UI
    "ui/app.py",
    # Tests
    "tests/__init__.py",
    "tests/conftest.py",
    "tests/test_cep.py",
    "tests/test_guardrails.py",
    "tests/test_no_action_gate.py",
    "tests/test_pipeline_smoke.py",
    # Docs
    "docs/research_log.md",
    "docs/solution_document.md",
    "docs/evaluation_report.md",
    # Diagrams
    "diagrams/architecture.mmd",
    # Ground truth
    "data/ground_truth/sample_ground_truth.json",
]

# Directories whose presence is a warning, not a failure
SOFT_DIRS = [
    "data/raw/scenario_01",
    "data/raw/scenario_02",
    "data/raw/scenario_03",
    "data/chroma",
    "output",
]

# Artifacts generated by running the pipeline
GENERATED_ARTIFACTS = [
    "output/inferred-events.jsonl",
    "output/inferred-events.json",
    "output/evaluation_report.json",
]

# Optional-but-nice artifacts
OPTIONAL_ARTIFACTS = [
    "diagrams/architecture.png",
    "diagrams/architecture.svg",
]


def check_files(r: Report):
    r.section("Files & Directories")

    for f in REQUIRED_FILES:
        p = _ROOT / f
        if p.exists():
            size = p.stat().st_size
            if size == 0:
                r.warn(f, "exists but is EMPTY")
            else:
                r.ok(f"{f}  ({size:,} bytes)")
        else:
            r.fail(f, "MISSING")

    for d in SOFT_DIRS:
        p = _ROOT / d
        if p.exists():
            r.ok(f"{d}/  (dir)")
        else:
            r.warn(f"{d}/", "missing — may need pipeline run")

    for f in GENERATED_ARTIFACTS:
        p = _ROOT / f
        if p.exists() and p.stat().st_size > 0:
            r.ok(f"{f}  ({p.stat().st_size:,} bytes)")
        elif p.exists():
            r.warn(f"{f}", "exists but empty — run pipeline")
        else:
            r.warn(f"{f}", "not yet generated — run pipeline")

    for f in OPTIONAL_ARTIFACTS:
        p = _ROOT / f
        if p.exists() and p.stat().st_size > 0:
            r.ok(f"{f}  ({p.stat().st_size:,} bytes)")
        else:
            r.warn(f"{f}", "optional — for README readability")


# ---------- section 2: imports ---------------------------------------------

MODULES = [
    "config.settings",
    "src.utils.logger",
    "src.utils.tracing",
    "src.utils.llm_client",
    "src.streaming.windows",
    "src.streaming.event_generator",
    "src.streaming.cep_engine",
    "src.streaming.features",
    "src.guardrails.scanner",
    "src.guardrails.pii",
    "src.guardrails.rbac",
    "src.memory.schemas",
    "src.memory.decay",
    "src.memory.working_memory",
    "src.memory.episodic_memory",
    "src.memory.semantic_memory",
    "src.memory.state_board",
    "src.agents.base_agent",
    "src.agents.schemas",
    "src.agents.usage_agent",
    "src.agents.support_agent",
    "src.agents.transaction_agent",
    "src.agents.kyc_agent",
    "src.agents.life_event_agent",
    "src.agents.synthesis_agent",
    "src.agents.debate_agent",
    "src.agents.judge_agent",
    "src.agents.action_agent",
    "src.agents.critique_agent",
    "src.orchestration.no_action_gate",
    "src.orchestration.pipeline",
    "src.hitl.approval_queue",
    "src.output.schema",
    "src.output.inferred_events_writer",
    "src.evaluation.metrics",
    "src.evaluation.scoring_harness",
]

CONTRACTS = [
    ("src.streaming.event_generator", ["RawEvent", "stream_events", "stream_scenario"]),
    ("src.streaming.cep_engine", ["CEPEngine", "WindowState"]),
    ("src.streaming.features", ["extract_features"]),
    ("src.guardrails.scanner", ["GuardrailScanner", "HardStop"]),
    ("src.guardrails.pii", ["PIITokenizer"]),
    ("src.guardrails.rbac", ["RBAC", "RBACViolation", "rbac_for", "ROLE_SCOPES"]),
    ("src.memory.decay", ["activation", "age_days"]),
    ("src.memory.episodic_memory", ["EpisodicMemory"]),
    ("src.memory.semantic_memory", ["SemanticMemory"]),
    ("src.memory.state_board", ["StateBoard"]),
    ("src.memory.working_memory", ["WorkingMemory"]),
    ("src.agents.base_agent", ["BaseAgent"]),
    ("src.agents.usage_agent", ["UsageAgent"]),
    ("src.agents.support_agent", ["SupportAgent"]),
    ("src.agents.transaction_agent", ["TransactionAgent"]),
    ("src.agents.kyc_agent", ["KYCAgent"]),
    ("src.agents.life_event_agent", ["LifeEventAgent"]),
    ("src.agents.synthesis_agent", ["SynthesisAgent"]),
    ("src.agents.debate_agent", ["RetentionDebateAgent", "GrowthDebateAgent"]),
    ("src.agents.judge_agent", ["JudgeAgent"]),
    ("src.agents.action_agent", ["ActionAgent"]),
    ("src.agents.critique_agent", ["CritiqueAgent"]),
    ("src.orchestration.no_action_gate", ["check_no_action", "NoActionResult"]),
    ("src.orchestration.pipeline", ["run_pipeline"]),
    ("src.hitl.approval_queue", ["HITLQueue", "HITLRequest"]),
    ("src.output.schema", ["InferredState", "Action", "HITLStatus", "ConfidenceBand", "Checkpoint"]),
    ("src.output.inferred_events_writer", ["InferredEventsWriter"]),
    ("src.evaluation.scoring_harness", ["ScoringHarness"]),
]


def check_imports(r: Report):
    r.section("Python Imports")
    for mod in MODULES:
        try:
            importlib.import_module(mod)
            r.ok(mod)
        except Exception as e:
            r.fail(mod, f"{type(e).__name__}: {e}")


def check_contracts(r: Report):
    r.section("Class / Function Contracts")
    for mod_name, symbols in CONTRACTS:
        try:
            mod = importlib.import_module(mod_name)
        except Exception as e:
            r.fail(mod_name, f"cannot import: {e}")
            continue
        for sym in symbols:
            if hasattr(mod, sym):
                r.ok(f"{mod_name}.{sym}")
            else:
                r.fail(f"{mod_name}.{sym}", "MISSING")


# ---------- section 3: config ----------------------------------------------

def check_config(r: Report):
    r.section("Configuration")
    try:
        from config.settings import settings
        r.ok(f"settings loaded, fast={settings.groq_model_fast}")
        for key in ("groq_api_key", "groq_model_fast", "groq_model_reason",
                    "groq_model_alt", "memory_decay_lambda"):
            if getattr(settings, key, None) is not None:
                r.ok(f"settings.{key}")
            else:
                r.fail(f"settings.{key}", "not set")
        if not settings.groq_api_key or settings.groq_api_key.startswith("your_"):
            r.warn("GROQ_API_KEY", "placeholder — needed for live pipeline runs")
    except Exception as e:
        r.fail("config.settings", f"{e}")

    try:
        from src.guardrails.scanner import GuardrailScanner
        s = GuardrailScanner()
        rules = list(s._rules.keys())
        if rules:
            r.ok(f"guardrails loaded, {len(rules)} rules: {rules}")
        else:
            r.fail("guardrails.yaml", "zero rules loaded")
    except Exception as e:
        r.fail("guardrails.yaml", f"{e}")

    try:
        import yaml
        with open(_ROOT / "config" / "agents.yaml", encoding="utf-8") as f:
            agents = (yaml.safe_load(f) or {}).get("agents", {})
        if agents:
            r.ok(f"agents.yaml loaded, {len(agents)} entries")
        else:
            r.fail("agents.yaml", "no 'agents' key")
    except Exception as e:
        r.fail("agents.yaml", f"{e}")


# ---------- section 4: artifacts -------------------------------------------

def check_artifacts(r: Report):
    r.section("Generated Artifacts")

    jsonl = _ROOT / "output" / "inferred-events.jsonl"
    if jsonl.exists() and jsonl.stat().st_size > 0:
        try:
            lines = [json.loads(l) for l in jsonl.read_text(encoding="utf-8").splitlines() if l.strip()]
            r.ok(f"inferred-events.jsonl: {len(lines)} checkpoints")
            required = {"as_of_time", "inferred_state", "confidence_band",
                        "action", "hitl_status"}
            for i, cp in enumerate(lines):
                missing = required - set(cp.keys())
                if missing:
                    r.fail(f"checkpoint {i}", f"missing fields: {missing}")
                else:
                    r.ok(f"checkpoint {i}: state={cp['inferred_state']}, "
                         f"action={cp['action']}, hitl={cp['hitl_status']}")
        except Exception as e:
            r.fail("inferred-events.jsonl", f"parse error: {e}")
    else:
        r.warn("inferred-events.jsonl", "not generated — run pipeline")

    rep = _ROOT / "output" / "evaluation_report.json"
    if rep.exists() and rep.stat().st_size > 0:
        try:
            data = json.loads(rep.read_text(encoding="utf-8"))
            r.ok(f"evaluation_report.json: overall_accuracy={data.get('overall_accuracy')}")
        except Exception as e:
            r.fail("evaluation_report.json", f"parse error: {e}")
    else:
        r.warn("evaluation_report.json", "not generated — run evaluation")


# ---------- section 5: docs ------------------------------------------------

DOC_MIN_BYTES = 400   # below this is suspicious for our docs

def check_docs(r: Report):
    r.section("Documentation Content")
    for doc in ["README.md", "docs/research_log.md",
                "docs/solution_document.md", "docs/evaluation_report.md"]:
        p = _ROOT / doc
        if not p.exists():
            r.fail(doc, "MISSING")
            continue
        size = p.stat().st_size
        if size < DOC_MIN_BYTES:
            r.warn(doc, f"only {size} bytes — likely incomplete")
        else:
            r.ok(f"{doc}  ({size:,} bytes)")


# ---------- section 6: tests -----------------------------------------------

def check_tests(r: Report):
    r.section("Test Suite (offline)")
    try:
        out = subprocess.run(
            [sys.executable, "-m", "pytest", "tests/", "-q",
             "-m", "not integration", "--no-header"],
            cwd=str(_ROOT), capture_output=True, text=True, timeout=120,
        )
        tail = (out.stdout or "").strip().splitlines()[-1] if out.stdout else ""
        if out.returncode == 0:
            r.ok(f"pytest: {tail}")
        else:
            r.fail("pytest", tail or f"exit {out.returncode}")
    except Exception as e:
        r.warn("pytest", f"could not run: {e}")


# ---------- main -----------------------------------------------------------

def main() -> int:
    print()
    print("=" * 78)
    print(" SUBMISSION VERIFICATION — Agentic Customer 360")
    print(f" Project root: {_ROOT}")
    print("=" * 78)

    r = Report()
    check_files(r)
    check_imports(r)
    check_contracts(r)
    check_config(r)
    check_artifacts(r)
    check_docs(r)
    check_tests(r)

    print()
    print("=" * 78)
    print(f" SUMMARY:  {r.passed} passed,  {r.failed} failed,  {r.warnings} warnings")
    print("=" * 78)

    if r.failures:
        print()
        print(" FAILURES (must fix before submit):")
        for f in r.failures:
            print(f"   • {f}")

    if r.warnings_list:
        print()
        print(" WARNINGS (optional but recommended):")
        for w in r.warnings_list:
            print(f"   • {w}")

    print()
    if r.failed == 0:
        print(" >>> READY TO SUBMIT <<<")
        return 0
    print(" >>> FIX FAILURES ABOVE BEFORE SUBMIT <<<")
    return 1


if __name__ == "__main__":
    sys.exit(main())